### ISSUE TITLE
DataTables: support "#" in printout statements and hide namespace prefixes

### ISSUE THREAD

**Issue by jaideraf** [SemanticMediaWiki/SemanticResultFormats#30]
Datatables is awesome, but it would be nice if it could support the same features of Broadtable like  additional personalization of the values with "#" and hidden namespace prefixes.

See: 
http://wikincat.org/wiki/User:Jaider/Página_de_testes
and
http://wikincat.org/wiki/User:Jaider/Página_de_testes?action=edit
(**same** query, **same** printout statements, different result formats)

Note the differences 
- in the values of the first and last columns
- in the values in the "status" column
- in the item column
- in the date columns

**Comment by gesinn-it** [comment]
@mwjames , @kghbln : preparing a fix (PR) for this. Would be cool if we could get this into 2.5.0 release...

**Comment by thomas-topway-it** [comment]
hello @jaideraf we would like to review this issue, but the posted examples don't work anymore, is there a way to update them ? thank you

**Comment by jaideraf** [comment]
Hello Thomas, I think I could reproduce the example from 2014:

See:
[http://wikincat.org/wiki/User:Jaideraf/Página_de_testes](http://wikincat.org/wiki/User:Jaideraf/P%C3%A1gina_de_testes)
and
[http://wikincat.org/wiki/User:Jaideraf/Página_de_testes?action=edit](http://wikincat.org/wiki/User:Jaideraf/P%C3%A1gina_de_testes?action=edit)

Note the differences

- in the values of the first and last columns (`datatables` shows the namespaces)
- in the item column (`datatables` hides the fragment part of the subojetcs, the ID)
- in the values in the "status" column (`datatables` does not support  the ["`<FORMATTER>`" of the boolean values](https://www.semantic-mediawiki.org/wiki/Help:Type_Boolean))
- in the date columns (`datatables` does not follow the `|sort=Has checked out date` parameter )

Thank you for looking at it

**Comment by thomas-topway-it** [comment]
hello @jaideraf thanks for your notes.
All of them should have been solved with a (hopefully) coming version of the Datatables result format. (rewritten from scratch)
You can try out it here

https://github.com/Knowledge-Wiki/SemanticResultFormats/tree/datatable-v2

The related documentation:
https://www.semantic-mediawiki.org/wiki/Help:Datatables_format_(v2)

A demo:
https://fina.knowledge.wiki/Catalogues_of_Numismatic_Collections

**Comment by jaideraf** [comment]
Hello @thomas-topway-it 
Wow, it looks very good, thank you! How can I test it? I tried 
```
git clone https://github.com/Knowledge-Wiki/SemanticResultFormats.git
git branch datatable-v2
```
But I still get the same result, I also cleared the cache, but nothing have changed. Should I have to change something else?

**Comment by thomas-topway-it** [comment]
I was using

`git clone -b datatable-v2 https://github.com/Knowledge-Wiki/SemanticResultFormats`

then the page has to be saved again with some edit
and the browser refreshed with hard refresh

**Comment by jaideraf** [comment]
Thanks, I got it. 
Just the `|sort=Has checked out date` ("Data de empréstimo" column) is still different from the `broadtable` (see above example). But it is a minor detail. May I close this issue or do you prefer to close when the merge occurs?

**Comment by thomas-topway-it** [comment]
@jaideraf it should have been solved ! This is the updated documentation https://www.semantic-mediawiki.org/wiki/Help:Datatables_format_(v2)

**Comment by jaideraf** [comment]
Perfect! Confirmed fix 😃
